### ISSUE TITLE
After some use, got the error "failed to claim device interface"

### ISSUE THREAD

**Issue by LittleWhite-tb** [Wolf2789/ROCCAT-SuoraFX-Effects-Animator#1]
Hello,

After exiting the software and opening it again, I got the error "Connecting to Suora FX... Err: failed to claim device interface"
Of course, if I wait some time, everything goes back to normal.

I suspect that you need more de-initialisation when closing the window or this can be because I don't switch off the connection button before exiting.

**Comment by Wolf2789** [comment]
Yes, I know. I'm working on some improvisation to the GUI, so you can claim device with switch and then when successfully connected execute lua code. I'm hoping to push new version soon.

**Comment by LittleWhite-tb** [comment]
This one looks fixed in the new version. 👍
