### ISSUE TITLE
Info on the protocol used for presets

### ISSUE THREAD

**Issue by LittleWhite-tb** [Wolf2789/ROCCAT-SuoraFX-Effects-Animator#5]
Hello,

Your tutorial (how to configure environment for capturing packets) was useful !
Here my findings (I don't know if you already have these) :

Preset header (?)  | Effect (from 0x01 to 0x0D) | Speed (from 0x01 to 0x0a) | Brightness (from 0x00 to 0x32) | Color (from 0x01 to 0x08 (only for effects with the color option)) | Option (like direction) | Undertemined (checksum ?)
--- | --- | --- | --- | --- | --- | ---
0x08 0x02 | 0x03 (plasma) | 0x01 | 0x10 | 0x08 | 0x01 | 0xcf

This explains why the color are some limited in the preset options. The last byte looks random to me. It changes when I am changing brightness and/or effect speed.

**Comment by Wolf2789** [comment]
### This is extremely helpful my friend :smile:

I didn't dig yet into this that much, but some of your explanations are close to mine.
For sure first byte (0x08) is the command to set preset. The second byte might be:
- 0x01 - set preset without changing it's options
- 0x02 - set preset with new options or something like that

And also there is some difference when setting custom preset. Before new setup is applied it needs to be sent with 0x120000080000005E packet, which might be

command | ? | ? | (? not sure) chunks of data to be received (8 * 64 bytes) | ? | ? | ? | maybe checksum
------------- | -- | -- | ------------------------------------------------------------------------- | -- | -- | -- | ----------------------
0x12 | 0x00 | 0x00 | 0x08 | 0x00 | 0x00 | 0x00 | 0x5E

and interrupts which actually sends preset data.

Can you send me some more info about what you've found out? At this moment I can't get Swamp to work and I don't know why, but I'm working on it.
Another problem I encountered lately was with my program. For some reason when I make _CustomPreset_ as a derivative class and hold custom preset data in it, it seems to not send this data to keyboard. It sets preset to custom but old data is used.
I think it has something to do with Vala, but I'm not sure yet.

**Comment by LittleWhite-tb** [comment]
What do you call Swamp ? Is that an effect (the ripple one ?).
Anyway, I got all the preset working, since I guessed how the checksum was implemented.
The checksum is just the sum of the 7 first bytes of the packet then inverted (aka 255 - the sum).

Now, I will look deeper in the custom lighting stuff.

**Comment by Wolf2789** [comment]
Sorry, my mistake. I was talking about Swarm.
Awesome work! I really appreciate your help.
Would you consider working with me on the application?
And also I'd like to talk to you somewhere outside issues section. Please contact with me via mail: wolf2789@gmail.com

And I think you guessed checksums just right. Tested once because lack of time, but I'm doing my best to get it working. Also I have some problems with new implementation of presets, so currently I'm working on getting it back to work. :)

**Comment by Wolf2789** [comment]
Changes, changes, changes...
- fixed newest implementation of presets
- added support for the rest of presets
- reimplemented lua api

..... so go ahead and check if it's working for you :smiley: 

Also implemented packet generating with calculated checksums thanks to you

**Comment by LittleWhite-tb** [comment]
The new version looks good to me. Good job !
Actually, we can't set the brightness for custom color set, isn't it ? 
~When running a custom preset, then, changing it again, the LEDs on are not switch off if we does not change their colors. I suggest to add a function to clear the actual layout.~ -> I missed the option

Finally, I suggest to move all information about the packets in a Wiki page (protocol documentation). Because this page became a general discussion.
